### ISSUE TITLE
No virtual method toMultimap()Ljava/util/Map; in class Lcom/squareup/okhttp/Headers

### ISSUE THREAD

**Issue by jmfayard** [parse-community/ParseInterceptors-Android#1]
Hello, 
I followed the instructions to add Parse Stetho Interceptor and my app crash when I open it

``` java
java.lang.NoSuchMethodError: No virtual method toMultimap()Ljava/util/Map; in class Lcom/squareup/okhttp/Headers; or its super classes (declaration of 'com.squareup.okhttp.Headers' appears in /data/app/com.smartmobilefactory.adviqo.debug-1/base.apk)
            at com.parse.ParseOkHttpClient.getParseHttpRequest(ParseOkHttpClient.java:189)
            at com.parse.ParseOkHttpClient.access$000(ParseOkHttpClient.java:40)
            at com.parse.ParseOkHttpClient$1.intercept(ParseOkHttpClient.java:214)
            at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:803)
            at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:684)
            at com.squareup.okhttp.Call.getResponse(Call.java:272)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
            at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
            at com.squareup.okhttp.Call.execute(Call.java:79)
            at com.parse.ParseOkHttpClient.executeInternal(ParseOkHttpClient.java:69)
            at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:158)
            at com.parse.ParseDecompressInterceptor.intercept(ParseDecompressInterceptor.java:30)
            at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:147)
            at com.parse.ParsePlugins$1.intercept(ParsePlugins.java:115)
            at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:147)
            at com.parse.ParseHttpClient.execute(ParseHttpClient.java:122)
            at com.parse.ParseRequest$3.then(ParseRequest.java:150)
            at com.parse.ParseRequest$3.then(ParseRequest.java:147)
            at bolts.Task$15.run(Task.java:825)
            at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
            at bolts.Task.completeAfterTask(Task.java:816)
            at bolts.Task.continueWithTask(Task.java:628)
            at bolts.Task.continueWithTask(Task.java:639)
            at bolts.Task$13.then(Task.java:731)
            at bolts.Task$13.then(Task.java:719)
            at bolts.Task$15.run(Task.java:825)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

Those are the dependencies I am using

``` gradle
    libs = [
            okhttp:                 "com.squareup.okhttp:okhttp:2.3.0",
            okhtturlconnection:     "com.squareup.okhttp:okhttp-urlconnection:2.3.0",
            parse:                  "com.parse:parse-android:1.10.2",
            stetho:                 "com.facebook.stetho:stetho:1.2.0",
            stethookhttp:           "com.facebook.stetho:stetho-okhttp:1.1.1",
            stethoparse:            "com.parse:parseinterceptors:0.0.1",
    ]
```

**Comment by wangmengyan95** [comment]
Hi @jmfayard, since we use some new apis in okHttp, could you update your okhttp to 2.5.0 and try again?

**Comment by jmfayard** [comment]
@wangmengyan95 yes, that works and is great :+1: 
Please document it

**Comment by wangmengyan95** [comment]
@jmfayard , great, hope you enjoy our new library. Document updated. I will close this issue.
